### PR TITLE
Fixes in pip install path

### PR DESCRIPTION
**Pull request by mparno**
@michael-c-brennan This should fix your issue, but could you checkout this branch and test a "local" pip build?   Just cd into the root MParT folder and type `pip install .`

### CODE REVIEW

**Comment by dannys4** [comment]
Works on Ubuntu.

**Comment by dannys4** [comment]
Michael and I talked- he had some issues installing on Ubuntu with 3.11 but could install on 3.10. For reference, my install works with 3.10 and 3.11. He could install on Mac just fine.

**Comment by dannys4** [comment]
Note in the command dump below that Michael's cmake couldn't find TPLTHREADS. I think this has to do with his G++ version being 7.5, which is not technically supported by us.
```
(mpart-pip) mcbrenn@acdl-System-Product-Name:~/Desktop/MParT$ pip install .
Processing /home/mcbrenn/Desktop/MParT
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: MParT
  Building wheel for MParT (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for MParT (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [84 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 7.5.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: /home/mcbrenn/Desktop/MParT/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /home/mcbrenn/Desktop/MParT/_skbuild/linux-x86_64-3.11/cmake-build
        Command:
          /tmp/pip-build-env-32bke1nc/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake /home/mcbrenn/Desktop/MParT -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/home/mcbrenn/Desktop/MParT/_skbuild/linux-x86_64-3.11/cmake-install -DPYTHON_VERSION_STRING:STRING=3.11.2 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-32bke1nc/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/include/python3.11 -DPYTHON_LIBRARY:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/lib/libpython3.11.so -DPython_EXECUTABLE:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/bin/python -DPython_ROOT_DIR:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip -DPython_INCLUDE_DIR:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/include/python3.11 -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/bin/python -DPython3_ROOT_DIR:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip -DPython3_INCLUDE_DIR:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/include/python3.11 -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-32bke1nc/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja -DKokkos_ENABLE_THREADS:BOOL=ON -DSKBUILD_LIB_RPATH=/home/mcbrenn/miniconda3/envs/mpart-pip/lib -DSKBUILD_SITE_PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/lib/python3.11/site-packages/ -DPYTHON_INSTALL_SUFFIX=bindings/python/package/ -DMPART_JULIA:BOOL=OFF -DMPART_MATLAB:BOOL=OFF -DMPART_BUILD_TESTS:BOOL=OFF -DMPART_PYTHON:BOOL=ON -DPYTHON_INSTALL_PREFIX= -DCMAKE_BUILD_TYPE:STRING=Release
      
      -- Will install MParT to /home/mcbrenn/Desktop/MParT/_skbuild/linux-x86_64-3.11/cmake-install
      -- PYTHON_INSTALL_PREFIX was not set by user, defaulting to /home/mcbrenn/Desktop/MParT/_skbuild/linux-x86_64-3.11/cmake-install/bindings/python/package/
      -- Python packages will be installed to /home/mcbrenn/Desktop/MParT/_skbuild/linux-x86_64-3.11/cmake-install/bindings/python/package/
      -- JULIA_INSTALL_PREFIX was not set by user, defaulting to /home/mcbrenn/Desktop/MParT/_skbuild/linux-x86_64-3.11/cmake-install/julia.
      -- Could not find Kokkos.  Fetching source.
      -- Setting default Kokkos CXX standard to 17
      -- The project name is: Kokkos
      -- Using -std=gnu++1z for C++17 extensions as feature
      -- Built-in Execution Spaces:
      --     Device Parallel: NoTypeDefined
      --     Host Parallel: Kokkos::Threads
      --       Host Serial: NONE
      --
      -- Architectures:
      CMake Error at /tmp/pip-build-env-32bke1nc/overlay/lib/python3.11/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find TPLTHREADS (missing: FOUND_THREADS)
      Call Stack (most recent call first):
        /tmp/pip-build-env-32bke1nc/overlay/lib/python3.11/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
        _skbuild/linux-x86_64-3.11/cmake-build/_deps/kokkos-src/cmake/Modules/FindTPLTHREADS.cmake:10 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
        _skbuild/linux-x86_64-3.11/cmake-build/_deps/kokkos-src/cmake/kokkos_functions.cmake:279 (FIND_PACKAGE)
        _skbuild/linux-x86_64-3.11/cmake-build/_deps/kokkos-src/cmake/kokkos_tpls.cmake:83 (KOKKOS_IMPORT_TPL)
        _skbuild/linux-x86_64-3.11/cmake-build/_deps/kokkos-src/cmake/kokkos_tribits.cmake:247 (INCLUDE)
        _skbuild/linux-x86_64-3.11/cmake-build/_deps/kokkos-src/CMakeLists.txt:188 (KOKKOS_SETUP_BUILD_ENVIRONMENT)
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-32bke1nc/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 634, in setup
          env = cmkr.configure(
                ^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-32bke1nc/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 332, in configure
          raise SKBuildError(
      
      An error occurred while configuring with CMake.
        Command:
          /tmp/pip-build-env-32bke1nc/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake /home/mcbrenn/Desktop/MParT -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/home/mcbrenn/Desktop/MParT/_skbuild/linux-x86_64-3.11/cmake-install -DPYTHON_VERSION_STRING:STRING=3.11.2 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-32bke1nc/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/include/python3.11 -DPYTHON_LIBRARY:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/lib/libpython3.11.so -DPython_EXECUTABLE:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/bin/python -DPython_ROOT_DIR:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip -DPython_INCLUDE_DIR:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/include/python3.11 -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/bin/python -DPython3_ROOT_DIR:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip -DPython3_INCLUDE_DIR:PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/include/python3.11 -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-32bke1nc/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja -DKokkos_ENABLE_THREADS:BOOL=ON -DSKBUILD_LIB_RPATH=/home/mcbrenn/miniconda3/envs/mpart-pip/lib -DSKBUILD_SITE_PATH=/home/mcbrenn/miniconda3/envs/mpart-pip/lib/python3.11/site-packages/ -DPYTHON_INSTALL_SUFFIX=bindings/python/package/ -DMPART_JULIA:BOOL=OFF -DMPART_MATLAB:BOOL=OFF -DMPART_BUILD_TESTS:BOOL=OFF -DMPART_PYTHON:BOOL=ON -DPYTHON_INSTALL_PREFIX= -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /home/mcbrenn/Desktop/MParT
        Working directory:
          /home/mcbrenn/Desktop/MParT/_skbuild/linux-x86_64-3.11/cmake-build
      Please see CMake's output for more information.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for MParT
Failed to build MParT
ERROR: Could not build wheels for MParT, which is required to install pyproject.toml-based projects
```

**Review by michael-c-brennan — APPROVED** [review]

**Comment by michael-c-brennan** [comment]
In the end `conda install -c conda-forge pthread-stubs` fixed the issue.

**Comment by dannys4** [comment]
To add, for some reason, it looks like `libpthread` wasn't installed. The above solves that problem, but it's definitely not the only way to solve such a problem.

**Pull request merged**
