### PR TITLE
Add Sphinx Tabs

### LINKED ISSUE #186: Python install docs got nuked
At some point, we (probably me?) butchered the python docs on the site, so you cannot see how to install mpart for python.

### PR DESCRIPTION
**Pull request by dannys4**
Fix #186 since we no longer use `sphinx-panels` for tabs.

### CODE REVIEW

**Comment by bonh** [comment]
Hi @dannys4! Isn't [`sphinx-design`](https://github.com/executablebooks/sphinx-design) the replacement to `sphinx-panels`?

**Comment by bonh** [comment]
Is their any advantage of `sphinx-tabs` vs. https://sphinx-design.readthedocs.io/en/latest/tabs.html? I do not know about any of these packages.

**Comment by dannys4** [comment]
I am not knowledgeable either, I just picked something with minimal code that does what I was looking for. I'm totally indifferent how we do it though, as long as we can do tabs (I really like them)

**Comment by bonh** [comment]
Yea, me too. So let's merge this.

**Review by bonh — APPROVED** [review]

**Pull request merged**
