### PR TITLE
Update MParT::Initialize so that Kokkos can update argc.

### LINKED ISSUE #130: Test results are not getting reported in CI

### PR DESCRIPTION
**Pull request by mparno**
Closes #130 

First argument to `MParT::Initialize` is now accepted by reference, which allows Kokkos to remove arguments from the command line inputs and allows Catch2 to function properly.

### CODE REVIEW

**Review by dannys4 — APPROVED** [review]
Assuming this passes tests, seems straightforward enough to me.

**Comment by bonh** [comment]
Does this change the bindings?

**Comment by dannys4** [comment]
It shouldn't, no.

**Comment by mparno** [comment]
For some reason, the `external-lib-test` workflow seems to be hanging indefinitely on the `./RunTests` step.   I'm working on debugging this.

**Comment by mparno** [comment]
@bonh No, this doesn't change the bindings at all.

**Review by bonh — APPROVED** [review]

**Pull request merged**
