### PR TITLE
Adding bindings for Julia affine and composed map classes

### PR DESCRIPTION
**Pull request by dannys4**
Commented out `EvaluateUntilK` due to odd `Layout` requirements.

### CODE REVIEW

**Comment by dannys4** [comment]
@rubiop can you try this out and make sure it compiles with Julia on your machine? Just want to get this on the grid at some point soon

**Comment by dannys4** [comment]
I'm currently encountering an issue with `ComposedMap`:
```julia
using MParT
A = randn(5,8)
B = randn(5,5)
pts = randn(8,2)
T1 = AffineMap(A)
T2 = AffineMap(B)
cmap = ComposedMap([T1,T2])
```

If you do `Evaluate(T1,pts)`, you get the right result, and `Evaluate(T2,A*pts)`, you get the right result, but for some reason, performing `Evaluate(cmap, pts)` throws a major error and crashes everything. Digging around a little bit, somehow it's performing a dGEMM $$C = A*B+C$$ with $$A\in\mathbb{R}^{5\times 8}$$, $$B\in\mathbb{R}^{8\times 2}$$ and $$C \in\mathbb{R}^{8\times 2}$$. I haven't found out why $$C$$ corresponds to that dimensional matrix, but I think it's safe to guess what the rest are according to the dimensions.

**Comment by dannys4** [comment]
Ah, `ComposedMap` isn't supposed to work with rectangles. My bad.

**Comment by dannys4** [comment]
looks like `jlmalloc` as written in the `JuliaArrayConversions` can sometimes allocate `NaN` values and, since we perform `C=AX+0C`, and IEEE states that `0*NaN=NaN`, we cannot recover from the original `NaN` value.

**Review by rubiop — APPROVED** [review]
tests succesful on my machine!

**Pull request merged**
