### PR TITLE
Add map training

### PR DESCRIPTION
**Pull request by dannys4**
This PR adds map objective and map training!!
- `MapObjective` is an abstract class to allow maps to train with an arbitrary objective. I'm thinking about how to get this working with external functions (i.e. from python/julia), but that'll be a bit. It keeps track of training and testing datasets since those are, in some sense, inherent to the fitting problem.
- `KLMapObjective` is a subclass of `MapObjective` that implements the usual KL map objective, from an arbitrary distribution
- `TrainOptions` are options largely for optimization with NLOpt as well as desired verbosity.
- `TrainMap` allows you to, well, train a given map according to the map objective and training options.

I will add bindings in a separate PR, since `TrainOptions` will likely be a pain.

### CODE REVIEW

**Comment by mparno** [comment]
@dannys4 Is this still a draft?

**Comment by dannys4** [comment]
I have to merge main into it, which is nontrivial. I can have it done in about 20 minutes or so

**Review by mparno — CHANGES_REQUESTED** [review]
I got a little ahead of things by reviewing #305 before this one.   @dannys4 Could you look at the comments for the `MapObjective.h` and `TrainMap.h` in #305?   Those are probably best addressed here.   The comments about the bindings can stay in #305.   Thanks!

**Comment by dannys4** [comment]
I found the requested changes in `TrainMap.h` agreeable, but I'm not as sure about the path forward for `MapObjective`-- feel free to continue the conversation here or there on those points.

**Review by mparno — APPROVED** [review]

**Pull request merged**
